services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://movie_user:movie_pass@db:5432/movie_db
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=movie_db
      - DB_USER=movie_user
      - DB_PASSWORD=movie_pass
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    command: >
      sh -c "echo 'Starting web service...' &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             echo 'Starting Django server...' &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_backup:/backup
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/staticfiles
      - ./ssl:/etc/ssl/certs
    depends_on:
      - web

  celery:
    build: .
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://movie_user:movie_pass@db:5432/movie_db
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=movie_db
      - DB_USER=movie_user
      - DB_PASSWORD=movie_pass
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media
    command: celery -A backend worker --loglevel=info

  celery-beat:
    build: .
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://movie_user:movie_pass@db:5432/movie_db
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=movie_db
      - DB_USER=movie_user
      - DB_PASSWORD=movie_pass
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media
    command: celery -A backend beat --loglevel=info

volumes:
  postgres_data:
  redis_data:
