# Generated by Django 4.2.21 on 2025-08-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('backdrop_path', models.CharField(blank=True, max_length=255)),
                ('vote_average', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0.0)),
                ('genre_ids', models.JSONField(default=list)),
                ('adult', models.BooleanField(default=False)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movies_movie',
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_user_watchlist',
            },
        ),
        migrations.CreateModel(
            name='UserMovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_user_rating',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_user_favorite',
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity'], name='movies_movi_popular_114287_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_average'], name='movies_movi_vote_av_ca6eee_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchlist',
            index=models.Index(fields=['user'], name='movies_user_user_id_aebfde_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchlist',
            index=models.Index(fields=['created_at'], name='movies_user_created_61c080_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='usermovierating',
            index=models.Index(fields=['user'], name='movies_user_user_id_800631_idx'),
        ),
        migrations.AddIndex(
            model_name='usermovierating',
            index=models.Index(fields=['rating'], name='movies_user_rating_32d5e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermovierating',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='userfavoritemovie',
            index=models.Index(fields=['user'], name='movies_user_user_id_dcff34_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoritemovie',
            index=models.Index(fields=['created_at'], name='movies_user_created_5bfc3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritemovie',
            unique_together={('user', 'movie')},
        ),
    ]
